# Generated by Django 5.2.4 on 2026-01-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Whether this property is visible to tenants in search results'),
        ),
    ]
