# Generated by Django 5.2.4 on 2026-01-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_property_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
