# Generated by Django 5.2.4 on 2026-01-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_property_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='map_embed',
            field=models.TextField(blank=True),
        ),
    ]
