# Generated by Django 5.2.4 on 2026-01-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact number for potential tenants', max_length=20),
        ),
    ]
