# Generated by Django 5.2.4 on 2026-01-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_property_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('bedsitter', 'Bedsitter'), ('1br', '1 Bedroom'), ('2br', '2 Bedroom'), ('3br', '3 Bedroom'), ('studio', 'Studio'), ('apartment', 'Apartment'), ('maisonette', 'Maisonette'), ('bungalow', 'Bungalow'), ('villa', 'Villa'), ('cottage', 'Cottage'), ('semi_detached', 'Semi-Detached'), ('duplex', 'Duplex'), ('townhouse', 'Townhouse'), ('terraced', 'Terraced'), ('penthouse', 'Penthouse'), ('boma', 'Boma'), ('hut', 'Hut'), ('manyatta', 'Manyatta'), ('tent', 'Tent'), ('mobile_home', 'Mobile Home'), ('container', 'Container'), ('smart_house', 'Smart House'), ('eco_house', 'Eco House'), ('floating', 'Floating House'), ('tree_house', 'Tree House')], max_length=20),
        ),
    ]
