# Generated by Django 5.2.4 on 2026-01-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('verification', 'Verification Fee'), ('property_upload', 'Property Upload'), ('promotion', 'Promoted Listing'), ('contact_access', 'Contact Access Fee')], max_length=20),
        ),
    ]
