# Generated by Django 5.2.4 on 2026-01-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from title for SEO-friendly URLs', max_length=250, null=True, unique=True),
        ),
    ]
