# Generated by Django 5.2.4 on 2026-01-11 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_property_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('single_room', 'Single Room'), ('bedsitter', 'Bedsitter'), ('1br', '1 Bedroom'), ('2br', '2 Bedroom'), ('3br', '3 Bedroom'), ('bungalow', 'Bungalow'), ('mansion', 'Mansion'), ('godown', 'Go-down'), ('shop', 'Shop')], max_length=20),
        ),
    ]
