# Generated by Django 5.2.4 on 2026-01-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_alter_property_bathrooms_alter_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdocument',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='id_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
