# Generated by Django 5.2.4 on 2026-01-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_verificationdocument_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='id_document',
            field=models.FileField(upload_to='verification_docs/'),
        ),
    ]
